text:
- name: content
- name: source
- name: resourceType
- name: resourceID
- name: patientID
numeric:
- name: start_index
vector:
- name: content_vector
  algorithm: HNSW
  datatype: FLOAT32
  dims: 384
  distance_metric: COSINE